language: c
os:
  - linux
  - osx
env:
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7
jobs:
  include:
    - env: PYTHON_VERSION=3.7 DOCS=1
before_install:
  - wget https://raw.githubusercontent.com/trichter/conda4travis/latest/conda4travis.sh -O conda4travis.sh
  - source conda4travis.sh
  - conda config --add channels conda-forge
  - if [[ $DOCS == 1 ]]; then
      DEP="sphinx sphinx_rtd_theme";
    else
      DEP="pytest-cov";
    fi
  - conda create -q -n testenv
      python=$PYTHON_VERSION obspy $DEP
  - conda activate testenv
  - conda list
install:
  - pip install stdb
  - pip install geographiclib
  - pip install -v --no-deps .
script:
  - if [[ $DOCS == 1 ]]; then
      cd docs; make html; touch _build/html/.nojekyll; cd ..;
    else
      mkdir empty; cd empty; pytest -v --cov=rfpy ../rfpy/tests/;
    fi
after_success:
  - if [[ $DOCS != 1 ]]; then
      bash <(curl -s https://codecov.io/bash);
    else
      openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in ".travis/github_deploy_key.enc" -out ".travis/github_deploy_key" -d;
    fi
notifications:
    email: false
deploy:
  provider: pages
  # provider: pages:git
  # edge:
  #   branch: octokit-latest
  edge: true # opt in to dpl v2
  deploy_key: .travis/github_deploy_key
  local_dir: docs/_build/html
  on:
    condition: $DOCS = 1